name: Caddy WAF Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget git build-essential

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Clone caddy-waf Repository
        run: |
          git clone https://github.com/fabriziosalmi/caddy-waf.git
          cd caddy-waf
          go mod tidy
          go get -v github.com/fabriziosalmi/caddy-waf github.com/caddyserver/caddy/v2 github.com/oschwald/maxminddb-golang
          wget https://git.io/GeoLite2-Country.mmdb

      - name: Build Caddy with caddy-waf
        run: |
          cd caddy-waf
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          xcaddy build --with github.com/fabriziosalmi/caddy-waf=./

      - name: Format Caddyfile
        run: |
          cd caddy-waf
          ./caddy fmt --overwrite

      - name: Test Caddy Run and Verify WAF Logs
        run: |
          cd caddy-waf
          ./caddy run &> caddy.log &
          sleep 5
          
          if ! pgrep -f "caddy run"; then
            echo "Caddy run failed"
            exit 1
          fi
          
          if ! grep -q "WAF initialized" caddy.log; then
            echo "WAF module not initialized correctly"
            cat caddy.log
            exit 1
          fi
          
          echo "Caddy WAF build and run successful with WAF initialized"

      - name: Clean Up
        if: always()
        run: |
          pkill -f "caddy run" || true
          echo "Cleaned up running Caddy instances"
