name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Get Dependencies
        run: go get -v ./...
        
      - name: Install Required tools
        run: go install github.com/caddyserver/caddy/v2@latest
      
      - name: Tidy modules
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=coverage.out ./...
