name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Get Dependencies
        run: go get -v ./...
        
      - name: Get Caddy Dependencies
        run: |
          go get github.com/caddyserver/caddy/v2/modules/caddyhttp/templates@v2.9.1
          go get github.com/caddyserver/caddy/v2/modules/caddyhttp/proxyprotocol@v2.9.1
          go get github.com/caddyserver/caddy/v2/modules/caddyhttp/tracing@v2.9.1
          go get github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver@v2.9.1
          go get github.com/smallstep/certificates/acme@v0.26.1
          
      - name: Build Caddy
        run: |
          go build -v -o caddy github.com/caddyserver/caddy/v2/cmd/caddy
          
      - name: Tidy modules
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v
