# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Required tools
      run: |
        go get github.com/caddyserver/caddy/v2
        go get github.com/caddyserver/caddy/v2/caddyconfig/caddyfile
        go get github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile
        go get github.com/caddyserver/caddy/v2/modules/caddyhttp
        go get github.com/oschwald/maxminddb-golang
        go get github.com/fsnotify/fsnotify
        go mod tidy
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
